# https://stefanscherer.github.io/use-appveyor-to-build-multi-arch-docker-image/
version: 1.0.{build}
image: 
#  - Visual Studio 2022
  - Ubuntu

configuration: Debug
platform: Any CPU

environment:
  matrix:
    # - ARCH: arm
    # - ARCH: arm64
    - ARCH: amd64

# matrix:
#   exclude:
#     - image: Visual Studio 2022
#       ARCH: arm
#     - image: Visual Studio 2022
#       ARCH: arm64

build_script:
    - ps: ./.appveyor/build.ps1

test_script:
    - ps: ./.appveyor/test.ps1

deploy_script:
    - ps: ./.appveyor/deploy.ps1


