#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.


# Learn about building .NET container images:
# https://github.com/dotnet/dotnet-docker/blob/main/samples/README.md
# https://github.com/dotnet/dotnet-docker/blob/main/samples/aspnetapp/Dockerfile.ubuntu
FROM mcr.microsoft.com/dotnet/sdk:7.0-jammy AS build
WORKDIR /src

LABEL maintainer="gaelgael5@gmail.com" github="https://github.com/Moleculars/Parrot"


WORKDIR /src/Black.Beard.Curl
# copy csproj in the image and restore packages
COPY Black.Beard.Curl/Black.Beard.Curl.csproj .
RUN dotnet restore --use-current-runtime
# copy csproj in the image and restore packages
COPY Black.Beard.Curl/* .
RUN dotnet build Black.Beard.Curl.csproj -c Release -o /app/build



WORKDIR /src/Black.Beard.OpenApi
# copy csproj in the image and restore packages
COPY Black.Beard.OpenApi/Black.Beard.OpenApi.csproj .
RUN dotnet restore --use-current-runtime
COPY Black.Beard.OpenApi/* .
RUN dotnet build -c Release -o /app/build


WORKDIR /src/Black.Beard.OpenApiServices
# copy csproj in the image and restore packages
COPY Black.Beard.OpenApiServices/Black.Beard.OpenApiServices.csproj .
RUN dotnet restore --use-current-runtime
COPY Black.Beard.OpenApiServices/ .
RUN dotnet build -c Release -o /app/build


WORKDIR /src/ParrotServices
# copy csproj in the image and restore packages
COPY Black.Beard.ParrotServices/Black.Beard.ParrotServices.csproj .
RUN dotnet restore --use-current-runtime
COPY Black.Beard.ParrotServices/* .
RUN dotnet publish Black.Beard.ParrotServices.csproj -c Release -o /app/build


EXPOSE 80
EXPOSE 443

ENTRYPOINT ["dotnet.exe", "Black.Beard.ParrotServices.dll"]