#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# https://github.com/dotnet/dotnet-docker/blob/main/samples/aspnetapp/Dockerfile.ubuntu
# Learn about building .NET container images:
FROM mcr.microsoft.com/dotnet/sdk:6.0-jammy AS build
LABEL maintainer="gaelgael5@gmail.com" github="https://github.com/Moleculars/Parrot"


WORKDIR /src/Black.Beard.Curl
COPY Black.Beard.Curl/ /src/Black.Beard.Curl
RUN dotnet restore --use-current-runtime

WORKDIR /src/Black.Beard.OpenApi
COPY Black.Beard.OpenApi/ /src/Black.Beard.OpenApi
RUN dotnet restore --use-current-runtime

WORKDIR /src/Black.Beard.OpenApiServices
COPY Black.Beard.OpenApiServices/ /src/Black.Beard.OpenApiServices
RUN dotnet restore --use-current-runtime

WORKDIR /src/Black.Beard.Web.Server
COPY Black.Beard.Web.Server/ /src/Black.Beard.Web.Server
RUN dotnet restore --use-current-runtime

WORKDIR /src/ParrotServices
COPY Black.Beard.ParrotServices/ /src/ParrotServices
RUN dotnet restore --use-current-runtime

RUN dotnet publish --use-current-runtime -r linux-x64 --no-restore -c Release -o /app
WORKDIR /app

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:6.0-jammy
WORKDIR /app
COPY --from=build /app .

ENV use_swagger=true
ENV trace_all=true
ENV use_telemetry=true

# EXPOSE 80	# with "mcr.microsoft.com/dotnet/aspnet:6.0"
EXPOSE 5000

ENTRYPOINT ["dotnet", "Black.Beard.ParrotServices.dll"]


